CREATE TABLE IF NOT EXISTS boards (
    id UUID PRIMARY KEY UNIQUE NOT NULL DEFAULT UUIDV7(),
    name TEXT NOT NULL,
    owner_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE CASCADE
);