CREATE TABLE IF NOT EXISTS cards (
    id UUID PRIMARY KEY UNIQUE NOT NULL DEFAULT UUIDV7(),
    title TEXT NOT NULL,
    content TEXT DEFAULT NULL,
    position NUMERIC NOT NULL DEFAULT 0,
    column_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    FOREIGN KEY(column_id) REFERENCES columns(id) ON DELETE CASCADE
);