CREATE TABLE IF NOT EXISTS columns (
    id UUID PRIMARY KEY UNIQUE NOT NULL DEFAULT UUIDV7(),
    name TEXT NOT NULL,
    position NUMERIC NOT NULL DEFAULT 0,
    board_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    FOREIGN KEY(board_id) REFERENCES boards(id) ON DELETE CASCADE
);